from datetime import datetime

# Real Row of data
NUTRIENTS_REAL_ROW = {
    "StationCode": "job09nut  ",
    "isSWMP": "P",
    "DateTimeStamp": "7/23/2002 8:50",
    "Historical": "1",
    "ProvisionalPlus": "1",
    "CollMethd": "2",
    "REP": "1",
    "F_Record": "",
    "PO4F": "0.0222",
    "F_PO4F": "<4>  ",
    "NH4F": "0.1048",
    "F_NH4F": "<4>  ",
    "NO2F": "0.0023",
    "F_NO2F": "<4>  ",
    "NO3F": "0.0098",
    "F_NO3F": "<4>  C                   ",
    "NO23F": "0.0121",
    "F_NO23F": "<4>  ",
    "CHLA_N": "",
    "F_CHLA_N": "<4>  M                   "
}


NUTRIENTS_PARSED_REAL_ROW = dict(
    StationCode="job09nut",
    isSWMP="P",
    DateTimeStamp=str(datetime(2002, 7, 23, 8, 50)),
    Historical=1,
    ProvisionalPlus=1,
    CollMethd=2,
    REP=1,
    F_Record=None,
    PO4F=0.0222,
    F_PO4F="<4>",
    NH4F=0.1048,
    F_NH4F="<4>",
    NO2F=0.0023,
    F_NO2F="<4>",
    NO3F=0.0098,
    F_NO3F="<4>  C",
    NO23F=0.0121,
    F_NO23F="<4>",
    CHLA_N=None,
    F_CHLA_N="<4>  M"
)

# Testing empty row
NUTRIENTS_EMPTY_ROW = {
    "StationCode": "",
    "isSWMP": "",
    "DateTimeStamp": "    ",
    "Historical": "  ",
    "ProvisionalPlus": "  ",
    "CollMethd": "",
    "REP": "  ",
    "F_Record": "",
    "PO4F": "",
    "F_PO4F": " ",
    "NH4F": "",
    "F_NH4F": "",
    "NO2F": "",
    "F_NO2F": "",
    "NO3F": "",
    "F_NO3F": "",
    "NO23F": " ",
    "F_NO23F": " ",
    "CHLA_N": "",
    "F_CHLA_N": ""
}

NUTRIENTS_PARSED_EMPTY_ROW = dict(
    StationCode=None,
    isSWMP=None,
    DateTimeStamp=None,
    Historical=None,
    ProvisionalPlus=None,
    CollMethd=None,
    REP=None,
    F_Record=None,
    PO4F=None,
    F_PO4F=None,
    NH4F=None,
    F_NH4F=None,
    NO2F=None,
    F_NO2F=None,
    NO3F=None,
    F_NO3F=None,
    NO23F=None,
    F_NO23F=None,
    CHLA_N=None,
    F_CHLA_N=None
)

WATERQUALITY_REAL_ROW = {
    "StationCode": "job06wq   ",
    "isSWMP": "P",
    "DateTimeStamp": "1/23/1998 16:00",
    "Historical": "1",
    "ProvisionalPlus": "0",
    "F_Record": "",
    "Temp": "29.3",
    "F_Temp": "<4> ",
    "SpCond": "58.8",
    "F_SpCond": "<4> ",
    "Sal": "39.2",
    "F_Sal": "<4> ",
    "DO_Pct": "",
    "F_DO_Pct": "<4> ",
    "DO_mgl": "",
    "F_DO_mgl": "<4> ",
    "Depth": "",
    "F_Depth": "<4> ",
    "cDepth": "",
    "F_cDepth": "",
    "Level": "",
    "F_Level": "<-1> ",
    "cLevel": "",
    "F_cLevel": "",
    "pH": "8.2",
    "F_pH": "<4> ",
    "Turb": "",
    "F_Turb": "<4> ",
    "ChlFluor": "",
    "F_ChlFluor": "<-1> "
}

WATERQUALITY_PARSED_REAL_ROW = dict(
    StationCode="job06wq",
    isSWMP="P",
    DateTimeStamp=str(datetime(1998, 1, 23, 16, 0)),
    Historical=1,
    ProvisionalPlus=0,
    F_Record=None,
    Temp=29.3,
    F_Temp="<4>",
    SpCond=58.8,
    F_SpCond="<4>",
    Sal=39.2,
    F_Sal="<4>",
    DO_Pct=None,
    F_DO_Pct="<4>",
    DO_mgl=None,
    F_DO_mgl="<4>",
    Depth=None,
    F_Depth="<4>",
    cDepth=None,
    F_cDepth=None,
    Level=None,
    F_Level="<-1>",
    cLevel=None,
    F_cLevel=None,
    pH=8.2,
    F_pH="<4>",
    Turb=None,
    F_Turb="<4>",
    ChlFluor=None,
    F_ChlFluor="<-1>"
)

METEOROLOGY_REAL_ROW = {
    "StationCode": "jobjbmet  ",
    "isSWMP": "P",
    "DatetimeStamp": "1/1/2007 0:00",
    "Historical": "1",
    "ProvisionalPlus": "1",
    "Frequency": "15",
    "F_Record": "",
    "ATemp": "",
    "F_ATemp": "<-2> (CSM)",
    "RH": "",
    "F_RH": "<-2> (CSM)",
    "BP": "",
    "F_BP": "<-2> (CSM)",
    "WSpd": "",
    "F_WSpd": "<-2> (CSM)",
    "MaxWSpd": "",
    "F_MaxWSpd": "<-1> ",
    "MaxWSpdT": "",
    "Wdir": "",
    "F_Wdir": "<-2> (CSM)",
    "SDWDir": "",
    "F_SDWDir": "<-1> ",
    "TotPAR": "",
    "F_TotPAR": "<-2> (CSM)",
    "TotPrcp": "",
    "F_TotPrcp": "<-2> (CSM)",
    "TotSoRad": "",
    "F_TotSoRad": "<-1> "
}

METEOROLOGY_PARSED_REAL_ROW = dict(
    StationCode="jobjbmet",
    isSWMP="P",
    DateTimeStamp=str(datetime(2007, 1, 1, 0, 0)),
    Historical=1,
    ProvisionalPlus=1,
    Frequency=15,
    F_Record=None,
    ATemp=None,
    F_ATemp="<-2> (CSM)",
    RH=None,
    F_RH="<-2> (CSM)",
    BP=None,
    F_BP="<-2> (CSM)",
    WSpd=None,
    F_WSpd="<-2> (CSM)",
    MaxWSpd=None,
    F_MaxWSpd="<-1>",
    MaxWSpdT=None,
    Wdir=None,
    F_Wdir="<-2> (CSM)",
    SDWDir=None,
    F_SDWDir="<-1>",
    TotPAR=None,
    F_TotPAR="<-2> (CSM)",
    TotPrcp=None,
    F_TotPrcp="<-2> (CSM)",
    TotSoRad=None,
    F_TotSoRad="<-1>"
)

SAMPLINGSTATIONS_REAL_ROW = {
    "Row": "1",
    "NERR Site ID ": "ace                                               ",
    "Station Code": "acebbnut  ",
    "Station Name": "Big Bay                                 ",
    "Lat Long": "32° 29' 38.76 N - 80° 19' 26.76 W",
    "Latitude ": "32.4941",
    " Longitude": "80.3241",
    " Status": "Inactive  ",
    " Active Dates": "Feb 2002-Dec 2014",
    " State": "sc        ",
    " Reserve Name": "Ashepoo Combahee Edisto Basin                     ",
    "Real Time": "",
    "HADS ID": "",
    "GMT Offset": "-5",
    "Station Type": "2",
    "Region": "2",
    "isSWMP": "P",
    "Parameters Reported": "PO4F,NH4F,NO23F,CHLA_N,DIN,NO2F,NO3F"
}

SAMPLINGSTATIONS_PARSED_REAL_ROW = dict(
    NERRSiteID="ace",
    StationCode="acebbnut",
    StationName="Big Bay",
    LatLong="32° 29' 38.76 N - 80° 19' 26.76 W",
    Latitude=32.4941,
    Longitude=80.3241,
    Status="Inactive",
    ActiveDates="Feb 2002-Dec 2014",
    State="sc",
    ReserveName="Ashepoo Combahee Edisto Basin",
    RealTime=None,
    HADSID=None,
    GMTOffset=-5,
    StationType=2,
    Region=2,
    isSWMP="P",
    ParametersReported="PO4F,NH4F,NO23F,CHLA_N,DIN,NO2F,NO3F"
)
